<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>

    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>

    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <Company>Billy</Company>
    <Product>DA Windower.NET</Product>
    <Authors>Billy</Authors>
    <Description>Windowed-mode wrapper for Dark Ages.</Description>
    <Copyright>Copyright © 2026 Billy</Copyright>

    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Optimize>true</Optimize>

    <OptimizationPreference>Size</OptimizationPreference>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>

    <DefineConstants Condition="'$(DAWND_LOG)' != 'false'">$(DefineConstants);DAWND_LOG</DefineConstants>

    <StackTraceSupport>false</StackTraceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <AutoreleasePoolSupport>false</AutoreleasePoolSupport>
    <DebuggerSupport>false</DebuggerSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
  </PropertyGroup>

</Project>
